name: Frontend and Backend CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  # ========================
  # FRONTEND
  # =========================
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build


  # =========================
  # BACKEND
  # =========================
  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Check backend code


      
        working-directory: backend
        run: node --check index.js

